_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.9.7
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.7
            "5": 0.18.0
            "8":
                - 1
                - 5
            "12": 0.18.0
            "13": linux-x86_64
dataset:
    value: wine_q
epochs:
    value: 20
